### ISSUE TITLE
install new packages without root permission

### ISSUE THREAD

**Issue by vanchung1995** [matthewfeickert/Docker-Python3-Ubuntu#12]
This version cannot install any packages that requires root permission

**Comment by matthewfeickert** [comment]
Hi @vanchung1995. I'm going to close this Issue as your statement isn't correct as the `docker` user has `sudo` powers

```
$ docker pull matthewfeickert/docker-python3-ubuntu:3.8.3
$ docker run --rm -it matthewfeickert/docker-python3-ubuntu:3.8.3
$ sudo apt update -qq -y
$ sudo apt install -qq -y cowsay
$ /usr/games/cowsay "user ${USER} has sudo powers! uh oh!"
 _____________________________________
< user docker has sudo powers! uh oh! >
 -------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
```

I'll note though that what I'm currently doing by giving `docker` user `sudo` powers is probably a _bad_ idea as you probably never want a container running with `sudo` powers unless you are 100% certain you know how it will be used.
