### ISSUE TITLE
Trouble with dependencies

### ISSUE THREAD

**Issue by garrii1010** [matthewfeickert/Docker-Python3-Ubuntu#21]
Hi there! Thanks 4 the repo! Its not working properly while installing all the dependencies. What libraries are the essentials one?

**Comment by garrii1010** [comment]
Thanks a lot! I will try it

**Comment by marc-mora** [comment]
thanks for what?

**Comment by marc-mora** [comment]
Have you tried reinstalling with the purge option? The repository works without problem for me

**Comment by garrii1010** [comment]
Bro pls

**Comment by matthewfeickert** [comment]
> Its not working properly while installing all the dependencies. What libraries are the essentials one?

@garrii1010 Can you please provide some more specific information on what "not working properly" means? Specifically what I'm looking for is the **text** of the commands and the errors that you're encountering **copy and pasted** here.

**Comment by garrii1010** [comment]
Sorry for the misunderstanding with the problem message I posted this afternoon. I was wrong and the problem was mine. I appreciate your quick response to the message!
